### ISSUE TITLE
Chat app on starter kit fails due to reference to older twilio library

### ISSUE THREAD

**Issue by saipanindra** [TwilioDevEd/sdk-starter-node#22]
On starting the server and navigating to `Chat`, noticed that the app hangs. This is due to failure in jwt.sign as the AccessToken add `headers` instead of `header`. This appears to be resolved in newer twilio versions. Upgrading dev dependency  to 3.2.0-alpha-1 resolved this error.

![twilio_chat_app_failure](https://user-images.githubusercontent.com/1620232/28395796-7e3a5abe-6cab-11e7-8e79-b93862f82276.png)

**Comment by well1791** [comment]
Hi @saipanindra

I'm going to close this issue as there no errors reported from the latest commits merged to master.
If you find still find an error for this please feel free to re-open this issue.

Thanks.
