### ISSUE TITLE
TypeError: Cannot read property 'v1' of undefined

### ISSUE THREAD

**Issue by dmilicic** [TwilioDevEd/sdk-starter-node#24]
I have been following this guide to the letter: https://www.twilio.com/docs/api/notify/guides/quickstart-android

I've set up the server locally and have given it the local ip address. While adding the binding name the server returns a 500 error with the following exception:

![screen shot 2017-07-22 at 20 24 57](https://user-images.githubusercontent.com/3181172/28494929-bd357804-6f3d-11e7-9580-6859f3bdc575.png)

**Comment by atbaker** [comment]
Hey @dmilicic - looks like we got a PR in to help with this.

I'm going to close this issue for now, but please reopen if you're still having trouble. And thank you for bringing it to our attention!
