### ISSUE TITLE
Misleading documentation

### ISSUE THREAD

**Issue by lukeasrodgers** [TwilioDevEd/sdk-starter-node#27]
Hi, apologies if this is not the best place to report this issue.

Here is my situation: my team and I were following the instructions here -- https://www.twilio.com/docs/api/notify/guides/messenger-notifications -- for the Facebook messenger integration quickstart.

About half way down the page, the docs mention a sample app on Github, linked to here: https://github.com/TwilioDevEd/notifications-quickstart-node, and subsequent directions in the aforementioned cos refer to files from that repository (e.g. `public/facebook-messenger.html`).

However, visiting that GH repo I see that it is deprecated, and refers the reader instead to https://github.com/TwilioDevEd/sdk-starter-node.

Yet at https://github.com/TwilioDevEd/sdk-starter-node there nothing about Facebook messenger integration, and the sample `public/facebook-messenger.html` is absent from the repo. You can see this file was deleted from the other repo at commit https://github.com/TwilioDevEd/notifications-quickstart-node/commit/8d1c19d09273f562987927f02711b2bcfa4c3747.

So, it seems like either this repo needs to be updated to reflect the docs at https://www.twilio.com/docs/api/notify/guides/messenger-notifications, or those docs need to be updated.

Thanks

**Comment by jefflinwood** [comment]
Thank you for your report! Merged Facebook messenger support into SDK Starter Node in https://github.com/TwilioDevEd/sdk-starter-node/pull/29
